### ISSUE TITLE
Outline and breadcrumbs navigation

### ISSUE THREAD

**Issue by labraxoid** [liwangqian/LuaCoderAssist#48]
Hello, 
Thanks for your great work! LuaCoderAssist is the best lua extension for VS Code!

**BUG in v.2.2.5 (  macOS 10.13.6 )**

In outline window when activated Follow Cursor mode not occur following the cursor in the editor window.

In breadcrumbs the symbols structure is not displayed correctly and current position of the cursor is not actual.

![bug001](https://user-images.githubusercontent.com/17118730/49950258-828e8680-ff08-11e8-9d1b-2b025dac2e5b.gif)

**Comment by labraxoid** [comment]
I have played with source code and and managed to fix but not for all the situation. Problem in incorrect definition of the **range** property in **LuaSymbol**.

**Comment by liwangqian** [comment]
well, thanks for the issue, I will debug this problem later.

**Comment by liwangqian** [comment]
@labraxoid This issue is partially resolved in **ver 2.2.6**. In case of defining symbols out of the range of a table, **breadcrumbs/symbol outline** cannot work correctly. The vscode api requires that, the range of the child of a table/class **must** in the range of the table/class, which is not the fact in lua language .
